### ISSUE TITLE
无法应对缩放攻击

### ISSUE THREAD

**Issue by jamiechoi1995** [fire-keeper/BlindWatermark#2]
比如我把图片缩小为原来的1/2，此时恢复水印失败
![out_wm](https://user-images.githubusercontent.com/13494034/61017265-21a72e00-a3c5-11e9-81f7-ab4b3c1b83ac.png)

**Comment by fire-keeper** [comment]
需要把图片缩放回原本大小, 现在这只能手动执行, 以后应该会出自动缩放的程序, 只能说在做了

**Comment by fire-keeper** [comment]
已经实现了把受到平移,旋转,缩放等攻击的图恢复到原始形状的算法了

**Comment by redpeer** [comment]
> 需要把图片缩放回原本大小, 现在这只能手动执行, 以后应该会出自动缩放的程序, 只能说在做了

tools里面的recovery方法，根本恢复不到原图啊，全是黑边
